---
driver:
  name: vagrant

platforms:
  - name: Heystaks-ubuntu-16.04
    driver:
      box: Heystaks/ubuntu-16.04

verifier:
  name: inspec

provisioner:
  name: salt_solo
  formula: hadoop
  require_chef: false
  dependencies:
    - name: java
      path: deps/java-formula

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
            - java
            - hadoop.hdfs.namenode
            - hadoop.hdfs.datanode
  - name: namenode
    driver:
      network:
        - ["private_network", {ip: "192.168.33.135"}]
    provisioner:
      state_top:
        base:
          '*':
            - java
            - hadoop.hdfs.namenode
      pillars:
        top.sls:
          base:
            '*':
              - hadoop
      pillars-from-files:
        hadoop.sls: pillar.example
  - name: datanode
    driver:
      network:
        - ["private_network", {ip: "192.168.33.136"}]
    provisioner:
      state_top:
        base:
          '*':
            - java
            - hadoop.hdfs.datanode
      pillars:
        top.sls:
          base:
            '*':
              - hadoop
      pillars-from-files:
        hadoop.sls: pillar.example
